import { DirectoryGridSkeleton } from "@/components/ui/directory-grid-skeleton";

/**
 * Loading component for directory category pages.
 * Displayed while the page content is being generated by Next.js App Router.
 * Provides visual feedback during ISR revalidation and initial page loads.
 */
export default function DirectoryCategoryLoading() {
  return (
    <div className="bg-background-secondary font-sans">
      <div className="mx-auto max-w-screen-xl px-4 py-16 sm:px-6 lg:px-8">
        {/* Header skeleton */}
        <div className="text-center">
          <div className="h-8 bg-background-tertiary rounded w-48 mx-auto animate-pulse mb-4" />
          <div className="h-4 bg-background-tertiary rounded w-64 mx-auto animate-pulse" />
        </div>

        {/* Directory grid skeleton */}
        <DirectoryGridSkeleton count={8} />
      </div>
    </div>
  );
}