"use server";

import { Octokit } from "@octokit/rest";
import { env } from "@/lib/env";
import { supabase } from "@/lib/supabase-client";

/**
 * Archive Story to MDX Server Action
 *
 * Handles archiving approved stories as MDX files in the GitHub repository by:
 * - Authenticating with GitHub using a Personal Access Token (PAT)
 * - Creating a commit with the MDX content in the stories directory
 * - Calling the backend API to mark the story as archived
 * - Providing detailed error handling and logging
 *
 * @param storyId - UUID of the story to archive
 * @param mdxContent - MDX content to commit (generated by admin UI)
 * @param slug - URL-friendly slug for the story filename
 * @param title - Story title (used in commit message)
 * @returns Promise with success flag, commit URL, or error message
 *
 * @see apps/web/.env.local.example - Environment variable configuration
 * @see apps/web/src/lib/backend-api.ts - Backend API integration patterns
 */
export async function archiveStoryToMDX(
  storyId: string,
  mdxContent: string,
  slug: string,
  title: string
): Promise<{ success: boolean; commitUrl?: string; error?: string }> {
  try {
    // 1. Validate environment variables
    const githubToken = process.env.GITHUB_TOKEN;
    if (!githubToken) {
      console.error(
        "[Archive Story] Missing GITHUB_TOKEN environment variable"
      );
      return {
        success: false,
        error:
          "GitHub integration not configured. Please contact an administrator.",
      };
    }

    const repoOwner = process.env.GITHUB_REPO_OWNER || "jcosta";
    const repoName = process.env.GITHUB_REPO_NAME || "nosilha";
    const branch = process.env.GITHUB_CONTENT_BRANCH || "main";

    // 2. Initialize Octokit client
    const octokit = new Octokit({
      auth: githubToken,
    });

    // 3. Get current branch SHA
    console.log(
      `[Archive Story] Fetching branch reference: ${repoOwner}/${repoName}@${branch}`
    );
    const { data: refData } = await octokit.rest.git.getRef({
      owner: repoOwner,
      repo: repoName,
      ref: `heads/${branch}`,
    });
    const currentSha = refData.object.sha;

    // 4. Get the current tree
    console.log(`[Archive Story] Fetching tree for SHA: ${currentSha}`);
    const { data: treeData } = await octokit.rest.git.getTree({
      owner: repoOwner,
      repo: repoName,
      tree_sha: currentSha,
    });

    // 5. Create a blob with the MDX content
    console.log(`[Archive Story] Creating blob for story: ${slug}`);
    const { data: blobData } = await octokit.rest.git.createBlob({
      owner: repoOwner,
      repo: repoName,
      content: Buffer.from(mdxContent, "utf-8").toString("base64"),
      encoding: "base64",
    });

    // 6. Create a new tree with the MDX file
    const filePath = `apps/web/content/stories/${slug}.mdx`;
    console.log(`[Archive Story] Creating tree with file: ${filePath}`);
    const { data: newTreeData } = await octokit.rest.git.createTree({
      owner: repoOwner,
      repo: repoName,
      base_tree: treeData.sha,
      tree: [
        {
          path: filePath,
          mode: "100644", // Regular file mode
          type: "blob",
          sha: blobData.sha,
        },
      ],
    });

    // 7. Create a commit
    const commitMessage = `feat(stories): archive story "${title}" to MDX

Story ID: ${storyId}
Slug: ${slug}

This story has been archived from the moderation queue and is now available
as static MDX content in the repository.`;

    console.log(
      `[Archive Story] Creating commit with message: ${commitMessage.split("\n")[0]}`
    );
    const { data: commitData } = await octokit.rest.git.createCommit({
      owner: repoOwner,
      repo: repoName,
      message: commitMessage,
      tree: newTreeData.sha,
      parents: [currentSha],
    });

    // 8. Update the branch reference
    console.log(
      `[Archive Story] Updating branch reference to: ${commitData.sha}`
    );
    await octokit.rest.git.updateRef({
      owner: repoOwner,
      repo: repoName,
      ref: `heads/${branch}`,
      sha: commitData.sha,
    });

    // 9. Mark the story as archived in the backend
    const commitUrl = commitData.html_url;
    console.log(`[Archive Story] Commit successful: ${commitUrl}`);

    try {
      await markStoryAsArchived(storyId, commitUrl);
      console.log(
        `[Archive Story] Story marked as archived in backend: ${storyId}`
      );
    } catch (backendError) {
      // Log the error but don't fail the entire operation
      // The commit succeeded, so we should report success to the user
      console.error(
        `[Archive Story] Failed to mark story as archived in backend:`,
        backendError
      );
      console.warn(
        `[Archive Story] Story ${storyId} was committed to GitHub but not marked as archived in database`
      );
    }

    // 10. Return success with commit URL
    return {
      success: true,
      commitUrl,
    };
  } catch (error: unknown) {
    console.error("[Archive Story] Unexpected error:", error);

    // Provide user-friendly error messages based on error type
    if (error instanceof Error) {
      // GitHub API errors
      if (error.message.includes("rate limit")) {
        return {
          success: false,
          error: "GitHub API rate limit exceeded. Please try again later.",
        };
      }

      if (
        error.message.includes("401") ||
        error.message.includes("authentication")
      ) {
        return {
          success: false,
          error:
            "GitHub authentication failed. Please check the GITHUB_TOKEN configuration.",
        };
      }

      if (
        error.message.includes("404") ||
        error.message.includes("not found")
      ) {
        return {
          success: false,
          error:
            "GitHub repository not found. Please check repository configuration.",
        };
      }

      // Return the specific error message for other known errors
      return {
        success: false,
        error: `Failed to archive story: ${error.message}`,
      };
    }

    // Generic fallback for unknown errors
    return {
      success: false,
      error:
        "An unexpected error occurred while archiving the story. Please try again.",
    };
  }
}

/**
 * Marks a story as archived in the backend database.
 *
 * Calls the backend API to update the story status to ARCHIVED and store the commit URL.
 * This ensures the story won't appear in the moderation queue anymore.
 *
 * @param storyId - UUID of the story to mark as archived
 * @param commitUrl - GitHub commit URL for reference
 * @throws Error if the API call fails
 */
async function markStoryAsArchived(
  storyId: string,
  commitUrl: string
): Promise<void> {
  // Get JWT token from Supabase session
  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (!session?.access_token) {
    throw new Error("Authentication required to mark story as archived");
  }

  // Call backend API to mark story as archived
  const endpoint = `${env.apiUrl}/api/v1/admin/stories/${storyId}/archive`;

  const response = await fetch(endpoint, {
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${session.access_token}`,
    },
    body: JSON.stringify({
      commitUrl,
      archivedAt: new Date().toISOString(),
    }),
    cache: "no-store",
  });

  if (!response.ok) {
    // Handle authentication errors
    if (response.status === 401) {
      await supabase.auth.signOut();
      throw new Error("Authentication expired. Please log in again.");
    }

    if (response.status === 403) {
      throw new Error("Access denied. Admin privileges required.");
    }

    if (response.status === 404) {
      throw new Error("Story not found in database");
    }

    // Try to get error message from response
    try {
      const errorData = await response.json();
      throw new Error(errorData.message || `API error: ${response.status}`);
    } catch (_parseError) {
      throw new Error(`Failed to mark story as archived (${response.status})`);
    }
  }

  console.log(
    `[Archive Story] Successfully marked story ${storyId} as archived`
  );
}
