services:
  db:
    image: postgres:16-alpine
    container_name: nosilha-postgres-local
    environment:
      POSTGRES_USER: nosilha
      POSTGRES_PASSWORD: nosilha-pass
      POSTGRES_DB: nosilha_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
