import { DirectoryGridSkeleton } from "@/components/ui/directory-grid-skeleton";

/**
 * Loading component for town detail pages.
 * Displayed while the page content is being generated by Next.js App Router.
 * Provides visual feedback during ISR revalidation and initial page loads.
 */
export default function TownPageLoading() {
  return (
    <div className="bg-background-secondary font-sans">
      <div className="mx-auto max-w-screen-xl px-4 py-16 sm:px-6 lg:px-8">
        {/* Page header skeleton */}
        <div className="text-center mb-16">
          <div className="h-10 bg-background-tertiary rounded w-64 mx-auto animate-pulse mb-4" />
          <div className="h-5 bg-background-tertiary rounded w-96 mx-auto animate-pulse" />
        </div>

        {/* Town info section skeleton */}
        <div className="mb-16 bg-background-primary rounded-lg p-6 animate-pulse">
          <div className="h-6 bg-background-tertiary rounded w-48 mb-4" />
          <div className="space-y-2">
            <div className="h-4 bg-background-tertiary rounded w-full" />
            <div className="h-4 bg-background-tertiary rounded w-3/4" />
            <div className="h-4 bg-background-tertiary rounded w-5/6" />
          </div>
        </div>

        {/* Directory entries section skeleton */}
        <div>
          <div className="h-6 bg-background-tertiary rounded w-56 mb-8 animate-pulse" />
          <DirectoryGridSkeleton count={6} />
        </div>
      </div>
    </div>
  );
}