import { DirectoryGridSkeleton } from "@/components/ui/directory-grid-skeleton";

/**
 * Loading component for town detail pages.
 * Displayed while the page content is being generated by Next.js App Router.
 * Provides visual feedback during ISR revalidation and initial page loads.
 */
export default function TownPageLoading() {
  return (
    <div className="bg-background-secondary font-sans">
      <div className="mx-auto max-w-screen-xl px-4 py-16 sm:px-6 lg:px-8">
        {/* Page header skeleton */}
        <div className="mb-16 text-center">
          <div className="bg-background-tertiary mx-auto mb-4 h-10 w-64 animate-pulse rounded" />
          <div className="bg-background-tertiary mx-auto h-5 w-96 animate-pulse rounded" />
        </div>

        {/* Town info section skeleton */}
        <div className="bg-background-primary mb-16 animate-pulse rounded-lg p-6">
          <div className="bg-background-tertiary mb-4 h-6 w-48 rounded" />
          <div className="space-y-2">
            <div className="bg-background-tertiary h-4 w-full rounded" />
            <div className="bg-background-tertiary h-4 w-3/4 rounded" />
            <div className="bg-background-tertiary h-4 w-5/6 rounded" />
          </div>
        </div>

        {/* Directory entries section skeleton */}
        <div>
          <div className="bg-background-tertiary mb-8 h-6 w-56 animate-pulse rounded" />
          <DirectoryGridSkeleton count={6} />
        </div>
      </div>
    </div>
  );
}
