package com.nosilha.core.media.domain

import com.google.cloud.firestore.annotation.DocumentId
import com.google.cloud.spring.data.firestore.Document
import java.time.Instant

/**
 * Represents the AI-generated metadata for an image stored in Google Cloud Storage.
 *
 * This data class is mapped to the "image-metadata" collection in Google Cloud Firestore.
 *
 * @param id The unique ID for the document, auto-generated and managed by Firestore.
 * @param gcsUrl The public URL of the corresponding image in Google Cloud Storage.
 * @param tags A list of descriptive tags generated by an AI vision service.
 * @param createdAt The timestamp indicating when this metadata record was created.
 */
@Document(collectionName = "image-metadata")
data class ImageMetadata(
    @DocumentId
    var id: String? = null,
    var gcsUrl: String = "",
    var tags: List<String> = emptyList(),
    var createdAt: Instant = Instant.now(),
)
