package com.nosilha.core.contentactions.services

import com.nosilha.core.contentactions.api.GenerateMdxRequest
import com.nosilha.core.contentactions.api.MdxContentDto
import com.nosilha.core.contentactions.api.MdxFrontmatter
import com.nosilha.core.contentactions.domain.StorySubmission
import org.slf4j.LoggerFactory
import org.springframework.context.annotation.Profile
import org.springframework.stereotype.Service
import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter

/**
 * Service interface for generating MDX content from story submissions.
 *
 * <p>This service transforms story submissions into MDX format suitable for Velite content
 * processing. It generates frontmatter metadata and markdown body content following the
 * Velite schema requirements.</p>
 *
 * <p><strong>Phase 1 Implementation:</strong></p>
 * <p>The initial implementation uses a mock service that generates valid MDX without
 * calling external AI APIs. This allows the system to function without API keys or costs
 * while providing a foundation for future AI enhancement.</p>
 *
 * <p><strong>Future Enhancement:</strong></p>
 * <p>Future implementations may integrate AI services for:
 * <ul>
 *   <li>Content enhancement and enrichment</li>
 *   <li>Automatic translation</li>
 *   <li>Tag generation</li>
 *   <li>Excerpt summarization</li>
 *   <li>Quality assessment</li>
 * </ul>
 * </p>
 */
interface MdxGenerationService {
    /**
     * Generates MDX content from a story submission.
     *
     * @param story The source story submission
     * @param options Optional generation parameters
     * @return MDX content DTO with frontmatter and markdown body
     */
    fun generate(
        story: StorySubmission,
        options: GenerateMdxRequest?,
    ): MdxContentDto
}

/**
 * Mock implementation of MDX generation service for Phase 1.
 *
 * <p>This implementation generates valid MDX content without calling external AI services.
 * It creates proper frontmatter following the Velite schema and formats the story content
 * as markdown.</p>
 *
 * <p><strong>Active Profiles:</strong></p>
 * <p>This bean is active when the "production" profile is NOT active, making it the default
 * for local development, testing, and staging environments.</p>
 *
 * <p><strong>Slug Generation:</strong></p>
 * <p>Slugs are generated by converting the title to lowercase and replacing non-alphanumeric
 * characters with hyphens. This ensures URL-friendly identifiers.</p>
 *
 * <p><strong>Schema Validation:</strong></p>
 * <p>The mock implementation always generates valid frontmatter (schemaValid = true) since
 * it follows the known Velite schema structure. Future AI implementations may need to
 * validate generated content against the schema.</p>
 */
@Service
@Profile("!production")
class MockMdxGenerationService : MdxGenerationService {
    private val logger = LoggerFactory.getLogger(MockMdxGenerationService::class.java)

    companion object {
        private val DATE_FORMATTER = DateTimeFormatter.ISO_LOCAL_DATE.withZone(ZoneId.of("UTC"))
    }

    /**
     * Generates MDX content from a story submission.
     *
     * <p>This mock implementation:
     * <ul>
     *   <li>Generates a URL-friendly slug from the title</li>
     *   <li>Creates frontmatter with all required Velite fields</li>
     *   <li>Formats the story content as markdown</li>
     *   <li>Combines frontmatter and content into complete MDX</li>
     *   <li>Marks the content as schema-valid</li>
     * </ul>
     * </p>
     *
     * @param story The source story submission
     * @param options Optional generation parameters (currently unused by mock)
     * @return MDX content DTO with valid frontmatter and markdown body
     */
    override fun generate(
        story: StorySubmission,
        options: GenerateMdxRequest?,
    ): MdxContentDto {
        logger.debug("Generating MDX for story {} (type: {})", story.id, story.storyType)

        // Generate URL-friendly slug from title
        val slug = generateSlug(story.title)

        // Build frontmatter
        val frontmatter =
            MdxFrontmatter(
                title = story.title,
                slug = slug,
                author = story.authorId,
                date = formatDate(story.createdAt ?: Instant.now()),
                language = "pt", // Default to Portuguese for Brava Island stories
                location = null, // Could be enhanced with related place name lookup
                storyType = story.storyType.name,
                tags = generateTags(story),
                excerpt = generateExcerpt(story.content),
            )

        // Build complete MDX source
        val mdxSource = buildMdxSource(frontmatter, story.content)

        logger.debug("Generated MDX for story {} with slug '{}'", story.id, slug)

        return MdxContentDto(
            storyId = story.id!!,
            slug = slug,
            mdxSource = mdxSource,
            frontmatter = frontmatter,
            schemaValid = true, // Mock always generates valid schema
            validationErrors = null,
            generatedAt = Instant.now(),
        )
    }

    /**
     * Generates a URL-friendly slug from a title.
     *
     * <p>Converts the title to lowercase and replaces all non-alphanumeric
     * characters with hyphens. Multiple consecutive hyphens are collapsed
     * to a single hyphen, and leading/trailing hyphens are removed.</p>
     *
     * @param title The story title
     * @return URL-friendly slug
     */
    private fun generateSlug(title: String): String =
        title
            .lowercase()
            .replace(Regex("[^a-z0-9]+"), "-")
            .trim('-')

    /**
     * Formats an Instant timestamp to ISO date string (YYYY-MM-DD).
     *
     * @param instant The timestamp to format
     * @return ISO date string in UTC
     */
    private fun formatDate(instant: Instant): String = DATE_FORMATTER.format(instant)

    /**
     * Generates tags based on story metadata.
     *
     * <p>Creates tags from:
     * <ul>
     *   <li>Story type (quick, full, guided)</li>
     *   <li>Template type (if applicable)</li>
     * </ul>
     * </p>
     *
     * <p>Future enhancement: Use AI to extract relevant tags from content.</p>
     *
     * @param story The story submission
     * @return List of tags
     */
    private fun generateTags(story: StorySubmission): List<String> {
        val tags = mutableListOf<String>()

        // Add story type tag
        tags.add(story.storyType.name.lowercase())

        // Add template type tag if present
        story.templateType?.let { templateType ->
            tags.add(templateType.name.lowercase())
        }

        return tags
    }

    /**
     * Generates an excerpt from the story content.
     *
     * <p>Takes the first 150 characters of the content and adds ellipsis if truncated.
     * Ensures the excerpt doesn't cut in the middle of a word.</p>
     *
     * <p>Future enhancement: Use AI to generate intelligent summaries.</p>
     *
     * @param content The story content
     * @return Brief excerpt for preview/SEO
     */
    private fun generateExcerpt(content: String): String {
        val maxLength = 150
        if (content.length <= maxLength) {
            return content
        }

        // Truncate and find last space to avoid cutting words
        val truncated = content.substring(0, maxLength)
        val lastSpace = truncated.lastIndexOf(' ')
        return if (lastSpace > 0) {
            truncated.substring(0, lastSpace) + "..."
        } else {
            "$truncated..."
        }
    }

    /**
     * Builds complete MDX source with frontmatter and content.
     *
     * <p>Format:</p>
     * <pre>
     * ---
     * title: "Story Title"
     * slug: "story-slug"
     * author: "author-id"
     * date: "2024-01-01"
     * language: "pt"
     * storyType: "FULL"
     * tags: ["full", "family"]
     * excerpt: "Story excerpt..."
     * ---
     *
     * Story content in markdown format...
     * </pre>
     *
     * @param frontmatter The frontmatter metadata
     * @param content The story content
     * @return Complete MDX file content
     */
    private fun buildMdxSource(
        frontmatter: MdxFrontmatter,
        content: String,
    ): String {
        val yaml =
            buildString {
                appendLine("---")
                appendLine("title: \"${escapeYaml(frontmatter.title)}\"")
                appendLine("slug: \"${frontmatter.slug}\"")
                appendLine("author: \"${frontmatter.author}\"")
                appendLine("date: \"${frontmatter.date}\"")
                appendLine("language: \"${frontmatter.language}\"")
                frontmatter.location?.let { appendLine("location: \"${escapeYaml(it)}\"") }
                appendLine("storyType: \"${frontmatter.storyType}\"")
                if (frontmatter.tags.isNotEmpty()) {
                    appendLine("tags: [${frontmatter.tags.joinToString(", ") { "\"$it\"" }}]")
                }
                frontmatter.excerpt?.let { appendLine("excerpt: \"${escapeYaml(it)}\"") }
                appendLine("---")
            }

        return yaml + "\n" + content
    }

    /**
     * Escapes special characters in YAML strings.
     *
     * <p>Handles quotes and backslashes to prevent YAML parsing errors.</p>
     *
     * @param text The text to escape
     * @return Escaped text safe for YAML
     */
    private fun escapeYaml(text: String): String = text.replace("\\", "\\\\").replace("\"", "\\\"")
}
