-- V9: Seed Reference Data
-- Seeds towns (16) and directory_entries (8) with research-corrected data.
-- Uses fixed UUIDs for idempotency.

-- Towns (16 settlements)
INSERT INTO towns (slug, name, description, latitude, longitude, population, elevation, founded, highlights, hero_image, gallery) VALUES
('nova-sintra', 'Nova Sintra',
    'Our mountain capital where cobblestone streets wind between flower-filled gardens and colonial sobrados tell stories of diaspora dreams realized',
    14.87111, -24.69611, '1,536 (2010 census)', '520m', 'Late 17th century',
    '["UNESCO Tentative List site", "Praca Eugenio Tavares", "Colonial sobrados", "Eugenio Tavares Museum"]',
    '/images/towns/nova-sintra-hero.jpg',
    '["/images/towns/nova-sintra-1.jpg", "/images/towns/nova-sintra-2.jpg", "/images/towns/nova-sintra-3.jpg"]'),
('furna', 'Furna',
    'Where the sea meets the land in a perfect volcanic embrace, this ancient harbor welcomes every visitor with the rhythms of working boats and ocean waves',
    14.88694, -24.68, '612 (2010 census)', 'Sea level', 'Early 18th century as major port',
    '["Volcanic crater harbor", "Fishing fleet", "Maritime festivals", "Nossa Senhora dos Navegantes"]',
    '/images/towns/furna-hero.jpg',
    '["/images/towns/furna-1.jpg", "/images/towns/furna-2.jpg", "/images/towns/furna-3.jpg"]'),
('faja-de-agua', 'Faja d''Agua',
    'Once our gateway to the world''s whaling ships, now a hidden paradise where volcanic pools offer perfect refuge from the Atlantic''s power',
    14.87306, -24.73194, '126 (2010 census)', 'Sea level-100m', '18th century as main port',
    '["Natural swimming pools", "Agricultural terraces", "Abandoned airport", "Emigrant monument"]',
    '/images/towns/faja-de-agua-hero.jpg',
    '["/images/towns/faja-de-agua-1.jpg", "/images/towns/faja-de-agua-2.jpg", "/images/towns/faja-de-agua-3.jpg"]'),
('nossa-senhora-do-monte', 'Nossa Senhora do Monte',
    'High among the clouds, this sacred place has drawn pilgrims for over 150 years, offering both spiritual solace and breathtaking views of our island home',
    14.85806, -24.71806, '271 (2010 census)', '642m', 'Parish established around 1826',
    '["Pilgrimage church", "August 15th festival", "Monte Fontainhas views", "Religious processions"]',
    '/images/towns/nossa-senhora-do-monte-hero.jpg',
    '["/images/towns/nossa-senhora-do-monte-1.jpg", "/images/towns/nossa-senhora-do-monte-2.jpg", "/images/towns/nossa-senhora-do-monte-3.jpg"]'),
('cachaco', 'Cachaco',
    'In Brava''s remote highlands, generations of families have perfected the art of cheese-making, creating flavors that carry the essence of our mountain pastures',
    14.83694, -24.69694, '228 (2010 census)', '592m', '19th century',
    '["Queijo do Cachaco", "Fogo island views", "Traditional cheese making", "Mountain isolation"]',
    '/images/towns/cachaco-hero.jpg',
    '["/images/towns/cachaco-1.jpg", "/images/towns/cachaco-2.jpg", "/images/towns/cachaco-3.jpg"]'),
('cova-joana', 'Cova Joana',
    'Cradled within an ancient crater''s embrace, this peaceful valley village showcases the harmony possible between volcanic power and human cultivation',
    14.86306, -24.71306, '183 (2010 census)', '400m', '19th century',
    '["Volcanic crater setting", "Colonial sobrados", "Hibiscus hedges", "Mountain tranquility"]',
    '/images/towns/cova-joana-hero.jpg',
    '["/images/towns/cova-joana-1.jpg", "/images/towns/cova-joana-2.jpg", "/images/towns/cova-joana-3.jpg"]'),
('cova-rodela', 'Cova Rodela',
    'A charming mountain village known for its iconic dragon tree in the main street and traditional maize cultivation in terraced fields',
    14.872, -24.705, '481 (2010 census)', '500m', '18th-19th century',
    '["Dragon tree landmark", "Maize cultivation", "Mountain walks to Monte Fontainhas", "Traditional agriculture"]',
    '/images/towns/cova-rodela-hero.jpg',
    '["/images/towns/cova-rodela-1.jpg", "/images/towns/cova-rodela-2.jpg"]'),
('campo-baixo', 'Campo Baixo',
    'A small mountain settlement featuring a unique ship-shaped chapel dedicated to Santa Maria, commemorating Cape Verde''s maritime heritage',
    14.848, -24.722, '169 (2010 census)', '400m', '19th century',
    '["Ship-shaped chapel", "Santa Maria monument", "Mountain views", "Nossa Senhora do Monte parish"]',
    '/images/towns/campo-baixo-hero.jpg',
    '["/images/towns/campo-baixo-1.jpg"]'),
('mato', 'Mato',
    'Perched high in the mountainous interior, this settlement represents the resilient spirit of Brava''s highland communities',
    14.857, -24.706, '441 (2010 census)', '770m', '19th century',
    '["Highland agriculture", "Mountain isolation", "Traditional farming", "Remote location"]',
    '/images/towns/mato-hero.jpg', '[]'),
('mato-grande', 'Mato Grande',
    'A quiet agricultural community in the eastern part of Brava, contributing to the island''s traditional farming heritage',
    14.85, -24.69, 'Small settlement', '400-500m', '19th century',
    '["Agricultural community", "Eastern location", "Traditional farming", "Sao Joao Baptista parish"]',
    '/images/towns/mato-grande-hero.jpg', '[]'),
('santa-barbara', 'Santa Barbara',
    'A small settlement dedicated to the patron saint of protection, nestled in Brava''s peaceful countryside',
    14.84, -24.70, 'Small settlement', '300-400m', '19th century',
    '["Religious heritage", "Rural setting", "Peaceful location", "Traditional architecture"]',
    '/images/towns/santa-barbara-hero.jpg', '[]'),
('tantum', 'Tantum',
    'One of the southernmost settlements in Cape Verde, known for its cable car connection and dramatic coastal location',
    14.83, -24.73, 'Small settlement', '200-300m', '19th century',
    '["Southernmost location", "Cable car system", "Coastal proximity", "Remote isolation"]',
    '/images/towns/tantum-hero.jpg',
    '["/images/towns/tantum-1.jpg"]'),
('vinagre', 'Vinagre',
    'A small rural settlement that contributes to Brava''s agricultural diversity in the island''s quiet interior',
    14.84, -24.71, 'Small settlement', '400m', '19th century',
    '["Agricultural focus", "Rural tranquility", "Traditional lifestyle", "Interior location"]',
    '/images/towns/vinagre-hero.jpg', '[]'),
('lem', 'Lem',
    'A peaceful settlement in Brava''s countryside, representing the island''s quiet rural heritage',
    14.85, -24.68, 'Small settlement', '300-400m', '19th century',
    '["Rural heritage", "Peaceful setting", "Traditional community", "Sao Joao Baptista parish"]',
    '/images/towns/lem-hero.jpg', '[]'),
('joao-da-noly', 'Joao da Noly',
    'A small settlement named after a local personality, part of Brava''s network of traditional communities',
    14.86, -24.69, 'Small settlement', '350m', '19th century',
    '["Named settlement", "Traditional community", "Rural location", "Historical significance"]',
    '/images/towns/joao-da-noly-hero.jpg', '[]'),
('tome-barraz', 'Tome Barraz',
    'A quiet settlement in Brava''s interior, maintaining the traditional ways of island life',
    14.85, -24.71, 'Small settlement', '450m', '19th century',
    '["Traditional lifestyle", "Interior settlement", "Rural community", "Mountain location"]',
    '/images/towns/tome-barraz-hero.jpg', '[]')
ON CONFLICT (slug) DO NOTHING;

-- Directory Entries (8 entries with fixed UUIDs)
INSERT INTO directory_entries (id, slug, name, description, category, town, latitude, longitude,
    phone_number, email, website, amenities, opening_hours, image_url, status) VALUES
('11111111-1111-1111-1111-111111111111', 'djababas-eco-lodge', 'Djabraba''s Eco-Lodge',
    'An eco-lodge offering sustainable mountain accommodation with traditional Cape Verdean hospitality and stunning views of the volcanic landscape.',
    'Hotel', 'Nova Sintra', 14.870500, -24.695535,
    '+238 285 26 94', 'marcogiandinoto@gmail.com', 'https://www.djabrabaeco-lodge.cv/',
    'Eco-Tourism,Mountain Views,Traditional Architecture,Cultural Immersion,Sustainable Practices',
    NULL, NULL, 'PUBLISHED'),
('22222222-2222-2222-2222-222222222222', 'faja-dagua', 'Faja d''Agua',
    'Historic fishing village famous for crystal-clear natural swimming pools carved from black volcanic rock. Site of the 1943 Matilde tragedy memorial and starting point of Cape Verdean emigration to America.',
    'Nature', 'Faja d''Agua', 14.873, -24.732,
    NULL, NULL, NULL, NULL, NULL, NULL, 'PUBLISHED'),
('33333333-3333-3333-3333-333333333333', 'igreja-nossa-senhora-do-monte', 'Igreja Nossa Senhora do Monte',
    'Historic pilgrimage church established c. 1826, representing Brava''s Madeiran devotional heritage. Currently under reconstruction (2023-present) with diaspora support. Annual festival: second weekend of August.',
    'Heritage', 'Nossa Senhora do Monte', 14.858, -24.718,
    NULL, NULL, NULL, NULL, NULL, '/images/directory/heritage/igreja-nossa-senhora-do-monte.jpg', 'PUBLISHED'),
('44444444-4444-4444-4444-444444444444', 'casa-eugenio-tavares', 'Casa Eugenio Tavares',
    'The preserved home of Cape Verde''s greatest poet, where morna was perfected and sodade given voice, connecting our island soul to hearts across the world.',
    'Heritage', 'Nova Sintra', 14.8699988107245, -24.698636386530936,
    '+238 2623385', 'nospatrimonio@gmail.com', 'http://www.eugeniotavares.org', NULL,
    'Mon-Fri 08:00-13:00, 14:00-16:00; Sat-Sun by appointment', NULL, 'PUBLISHED'),
('55555555-5555-5555-5555-555555555555', 'praca-eugenio-tavares', 'Praca Eugenio Tavares',
    'The cultural heart of Nova Sintra, this historic square honors poet Eugenio Tavares (1867-1930) with a bronze statue inaugurated June 24, 2002. Features a traditional music pavilion and Portuguese pavement mosaics. Part of the UNESCO-nominated Nova Sintra Historic Centre.',
    'Heritage', 'Nova Sintra', 14.871352344591463, -24.695556421325776,
    NULL, NULL, NULL, NULL, NULL, NULL, 'PUBLISHED'),
('66666666-6666-6666-6666-666666666666', 'pousada-nova-sintra', 'Pousada Nova Sintra',
    'An authentic family-run pousada in the heart of Nova Sintra, offering traditional Cape Verdean hospitality with views of the surrounding mountains and cultural immersion experiences.',
    'Hotel', 'Nova Sintra', 14.86868289, -24.6942991,
    '+238 262 0444', NULL, NULL, 'Family-Run,Cultural Immersion,Mountain Views,Traditional Breakfast,Local Guides',
    NULL, NULL, 'PUBLISHED'),
('77777777-7777-7777-7777-777777777777', 'pensao-paulo', 'Pensao Paulo',
    'A welcoming pensao offering comfortable accommodation and authentic local experience in Nova Sintra, where guests become part of the Brava Island community.',
    'Hotel', 'Nova Sintra', 14.870085, -24.695388,
    '+238 285 13 12', 'pensaopaulo@hotmail.com', 'https://pgbspensao.cv',
    'Community Experience,Local Hospitality,Central Location,Traditional Architecture',
    NULL, NULL, 'PUBLISHED'),
('88888888-8888-8888-8888-888888888888', 'nos-raiz', 'Nos Raiz',
    'A multi-service residence in the coastal village of Faja d''Agua, offering cozy accommodation with bar and restaurant services. The name means "Our Roots," reflecting authentic Cape Verdean hospitality.',
    'Hotel', 'Faja d''Agua', 14.873, -24.732,
    '+238 977 9998', 'nosraizcv@gmail.com', NULL, NULL, NULL, NULL, 'PUBLISHED')
ON CONFLICT (slug) DO NOTHING;
