# Local development profile configuration
# This profile is designed to work with the local PostgreSQL Docker container

spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/nosilha_db
    username: nosilha
    password: nosilha-pass
    # Connection Pool Configuration (HikariCP)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  # Flyway Configuration
  flyway:
    enabled: true

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    gcp:
      credentials:
        location: "classpath:sa-key.json"
gcp:
  gcs-bucket-name: "nosilha-com-media-storage-useast1"

supabase:
  jwt-secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxcGdibXJnd2JleHhsZGVva2l1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDA5NzQzOSwiZXhwIjoyMDY1NjczNDM5fQ.Fgqu1WgVEz8SJpaN2CYa08z0yePJG7nX86Nj-yqAbdw
